Traceback (most recent call last):
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from imageio.v3 import imread, imwrite # conda install conda-forge::imageio
import cv2; from mpl_toolkits.mplot3d import Axes3D

# 国土地理院の地理院情報をもとに3Dレンダリングする
def draw_jp_map(texture, dem, height):
    l=512
    size=(l,l)
    # 標高データをlxlピクセルに解像度変換する
    z = cv2.resize(dem, size)
    # 地図画像データも同様にlxlピクセルに解像度変換する
    tex = cv2.resize(np.delete(texture, 3, axis=2), size)
    # 描画する高さ・色データを作成する
    x = y = np.linspace(0, l, l)
    x, y = np.meshgrid(x, y)
    x = np.ravel(x);y = np.ravel(y);z = np.ravel(z)
    c=np.reshape(tex,(l*l,3))
    for idx, z_ in enumerate(z):
        if z_< height:
          z[idx]=0.0
          c[idx]=[0,0,1]
    fig=plt.figure(figsize=[20,20])
    ax=fig.add_subplot(111,projection='3d')
    # レンダリングする標高レンジを決める
    ax.set_zlim(20,120)
    # レンダリングする視点を決める
    # elevはz軸方向から見た仰角，azimはx, y軸方向の方位角．
    ax.view_init(elev=30, azim=240)
    ax.invert_yaxis()
    ax.scatter3D(x,y,z,
        s=8,alpha=0.6,
        c=np.reshape(tex,(l*l,3)))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mimageio[39;00m[38;5;21;01m.[39;00m[38;5;21;01mv3[39;00m [38;5;28;01mimport[39;00m imread, imwrite [38;5;66;03m# conda install conda-forge::imageio[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mcv2[39;00m; [38;5;28;01mfrom[39;00m [38;5;21;01mmpl_toolkits[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmplot3d[39;00m [38;5;28;01mimport[39;00m Axes3D

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/matplotlib/__init__.py:161[0m
[1;32m    157[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpackaging[39;00m[38;5;21;01m.[39;00m[38;5;21;01mversion[39;00m [38;5;28;01mimport[39;00m parse [38;5;28;01mas[39;00m parse_version
[1;32m    159[0m [38;5;66;03m# cbook must import matplotlib only within function[39;00m
[1;32m    160[0m [38;5;66;03m# definitions, so it is safe to import from it here.[39;00m
[0;32m--> 161[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m _api, _version, cbook, _docstring, rcsetup
[1;32m    162[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcbook[39;00m [38;5;28;01mimport[39;00m sanitize_sequence
[1;32m    163[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_api[39;00m [38;5;28;01mimport[39;00m MatplotlibDeprecationWarning

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/matplotlib/rcsetup.py:27[0m
[1;32m     25[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m _api, cbook
[1;32m     26[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcbook[39;00m [38;5;28;01mimport[39;00m ls_mapper
[0;32m---> 27[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcolors[39;00m [38;5;28;01mimport[39;00m Colormap, is_color_like
[1;32m     28[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_fontconfig_pattern[39;00m [38;5;28;01mimport[39;00m parse_fontconfig_pattern
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_enums[39;00m [38;5;28;01mimport[39;00m JoinStyle, CapStyle

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/matplotlib/colors.py:52[0m
[1;32m     49[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumbers[39;00m [38;5;28;01mimport[39;00m Real
[1;32m     50[0m [38;5;28;01mimport[39;00m [38;5;21;01mre[39;00m
[0;32m---> 52[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPIL[39;00m [38;5;28;01mimport[39;00m Image
[1;32m     53[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPIL[39;00m[38;5;21;01m.[39;00m[38;5;21;01mPngImagePlugin[39;00m [38;5;28;01mimport[39;00m PngInfo
[1;32m     55[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpl[39;00m

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/Image.py:82[0m
[1;32m     73[0m MAX_IMAGE_PIXELS [38;5;241m=[39m [38;5;28mint[39m([38;5;241m1024[39m [38;5;241m*[39m [38;5;241m1024[39m [38;5;241m*[39m [38;5;241m1024[39m [38;5;241m/[39m[38;5;241m/[39m [38;5;241m4[39m [38;5;241m/[39m[38;5;241m/[39m [38;5;241m3[39m)
[1;32m     76[0m [38;5;28;01mtry[39;00m:
[1;32m     77[0m     [38;5;66;03m# If the _imaging C module is not present, Pillow will not load.[39;00m
[1;32m     78[0m     [38;5;66;03m# Note that other modules should not refer to _imaging directly;[39;00m
[1;32m     79[0m     [38;5;66;03m# import Image and use the Image.core variable instead.[39;00m
[1;32m     80[0m     [38;5;66;03m# Also note that Image.core is not a publicly documented interface,[39;00m
[1;32m     81[0m     [38;5;66;03m# and should be considered private and subject to change.[39;00m
[0;32m---> 82[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m _imaging [38;5;28;01mas[39;00m core
[1;32m     84[0m     [38;5;28;01mif[39;00m __version__ [38;5;241m!=[39m [38;5;28mgetattr[39m(core, [38;5;124m"[39m[38;5;124mPILLOW_VERSION[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m):
[1;32m     85[0m         msg [38;5;241m=[39m (
[1;32m     86[0m             [38;5;124m"[39m[38;5;124mThe _imaging extension was built for another version of Pillow or PIL:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     87[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCore version: [39m[38;5;132;01m{[39;00m[38;5;28mgetattr[39m(core,[38;5;250m [39m[38;5;124m'[39m[38;5;124mPILLOW_VERSION[39m[38;5;124m'[39m,[38;5;250m [39m[38;5;28;01mNone[39;00m)[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     88[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mPillow version: [39m[38;5;132;01m{[39;00m__version__[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     89[0m         )

[0;31mImportError[0m: dlopen(/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: <DB29B4E0-5E05-3F26-ABC5-79A53D06F310> /opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so
  Reason: tried: '/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/../../../libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/../../../libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/bin/../lib/libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/bin/../lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)

